service: pysprinter

frameworkVersion: '3'

package:
  exclude:
    - test/**
    - README.md
    - cli.py
    - serverless.yml
    - .gitignore

provider:
  name: aws
  stage: dev
  runtime: python3.10
  region: us-east-1

functions:
  core:
    handler: handler.handler
    memorySize: 3008 # appears to be the max without a support request
    ephemeralStorageSize: 10240 # for caching package versions
    timeout: 600 # 10 minutes - who knows what the user will want